---

version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:latest
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.1
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
  galaxy:
    collections:
    - name: ansible.posix
      version: 1.5.4
    - name: ansible.utils
      version: 4.1.0
    - name: ansible.windows
      version: 2.3.0
    - name: community.general
      version: 9.1.0
